{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting git+https://github.com/shahashka/SP-GIES\r\n",
      "  Cloning https://github.com/shahashka/SP-GIES to /private/var/folders/hr/9_dgjtbx6ll7bkdgtm_4dkl00000gn/T/pip-req-build-y57jj4y7\r\n",
      "  Running command git clone --filter=blob:none --quiet https://github.com/shahashka/SP-GIES /private/var/folders/hr/9_dgjtbx6ll7bkdgtm_4dkl00000gn/T/pip-req-build-y57jj4y7\r\n",
      "  Resolved https://github.com/shahashka/SP-GIES to commit b8302f9d0b5d995e0e371f5c7c61609b437fe939\r\n",
      "  Running command git submodule update --init --recursive -q\r\n",
      "  Preparing metadata (setup.py) ... \u001b[?25l-\b \berror\r\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\r\n",
      "  \r\n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\r\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\r\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[65 lines of output]\u001b[0m\r\n",
      "  \u001b[31m   \u001b[0m /private/var/folders/hr/9_dgjtbx6ll7bkdgtm_4dkl00000gn/T/pip-req-build-y57jj4y7/setup.py:9: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,\r\n",
      "  \u001b[31m   \u001b[0m `setuptools.config.read_configuration` became deprecated.\r\n",
      "  \u001b[31m   \u001b[0m \r\n",
      "  \u001b[31m   \u001b[0m For the time being, you can use the `setuptools.config.setupcfg` module\r\n",
      "  \u001b[31m   \u001b[0m to access a backward compatible API, but this module is provisional\r\n",
      "  \u001b[31m   \u001b[0m and might be removed in the future.\r\n",
      "  \u001b[31m   \u001b[0m \r\n",
      "  \u001b[31m   \u001b[0m   conf_dict = read_configuration(setup_cfg)\r\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\r\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\r\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\r\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/hr/9_dgjtbx6ll7bkdgtm_4dkl00000gn/T/pip-req-build-y57jj4y7/setup.py\", line 9, in <module>\r\n",
      "  \u001b[31m   \u001b[0m     conf_dict = read_configuration(setup_cfg)\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/__init__.py\", line 29, in _wrapper\r\n",
      "  \u001b[31m   \u001b[0m     return fn(*args, **kwargs)\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/setupcfg.py\", line 64, in read_configuration\r\n",
      "  \u001b[31m   \u001b[0m     handlers = _apply(dist, filepath, filenames, ignore_option_errors)\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/setupcfg.py\", line 96, in _apply\r\n",
      "  \u001b[31m   \u001b[0m     handlers = parse_configuration(\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/setupcfg.py\", line 174, in parse_configuration\r\n",
      "  \u001b[31m   \u001b[0m     meta.parse()\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/setupcfg.py\", line 496, in parse\r\n",
      "  \u001b[31m   \u001b[0m     section_parser_method(section_options)\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/setupcfg.py\", line 470, in parse_section\r\n",
      "  \u001b[31m   \u001b[0m     self[name] = value\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/setupcfg.py\", line 278, in __setitem__\r\n",
      "  \u001b[31m   \u001b[0m     value = parser(value)\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/setupcfg.py\", line 602, in _parse_version\r\n",
      "  \u001b[31m   \u001b[0m     return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/setupcfg.py\", line 411, in _parse_attr\r\n",
      "  \u001b[31m   \u001b[0m     package_dir.update(self.ensure_discovered.package_dir)\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/_collections_abc.py\", line 826, in __iter__\r\n",
      "  \u001b[31m   \u001b[0m     yield from self._mapping\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/expand.py\", line 462, in __iter__\r\n",
      "  \u001b[31m   \u001b[0m     return iter(self._target())\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/expand.py\", line 452, in _target\r\n",
      "  \u001b[31m   \u001b[0m     self._value = self._obtain()\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/expand.py\", line 422, in _get_package_dir\r\n",
      "  \u001b[31m   \u001b[0m     self()\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/config/expand.py\", line 412, in __call__\r\n",
      "  \u001b[31m   \u001b[0m     self._dist.set_defaults(name=False)  # Skip name, we can still be parsing\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/discovery.py\", line 341, in __call__\r\n",
      "  \u001b[31m   \u001b[0m     self._analyse_package_layout(ignore_ext_modules)\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/discovery.py\", line 374, in _analyse_package_layout\r\n",
      "  \u001b[31m   \u001b[0m     or self._analyse_flat_layout()\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/discovery.py\", line 431, in _analyse_flat_layout\r\n",
      "  \u001b[31m   \u001b[0m     return self._analyse_flat_packages() or self._analyse_flat_modules()\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/discovery.py\", line 437, in _analyse_flat_packages\r\n",
      "  \u001b[31m   \u001b[0m     self._ensure_no_accidental_inclusion(top_level, \"packages\")\r\n",
      "  \u001b[31m   \u001b[0m   File \"/Applications/anaconda3/envs/sp_gies/lib/python3.9/site-packages/setuptools/discovery.py\", line 467, in _ensure_no_accidental_inclusion\r\n",
      "  \u001b[31m   \u001b[0m     raise PackageDiscoveryError(cleandoc(msg))\r\n",
      "  \u001b[31m   \u001b[0m setuptools.errors.PackageDiscoveryError: Multiple top-level packages discovered in a flat-layout: ['cupc', 'data', 'R_scripts', 'causal_learning', 'CausalDiscoveryToolbox'].\r\n",
      "  \u001b[31m   \u001b[0m \r\n",
      "  \u001b[31m   \u001b[0m To avoid accidental inclusion of unwanted files or directories,\r\n",
      "  \u001b[31m   \u001b[0m setuptools will not proceed with this build.\r\n",
      "  \u001b[31m   \u001b[0m \r\n",
      "  \u001b[31m   \u001b[0m If you are trying to create a single distribution with multiple packages\r\n",
      "  \u001b[31m   \u001b[0m on purpose, you should not rely on automatic discovery.\r\n",
      "  \u001b[31m   \u001b[0m Instead, consider the following options:\r\n",
      "  \u001b[31m   \u001b[0m \r\n",
      "  \u001b[31m   \u001b[0m 1. set up custom discovery (`find` directive with `include` or `exclude`)\r\n",
      "  \u001b[31m   \u001b[0m 2. use a `src-layout`\r\n",
      "  \u001b[31m   \u001b[0m 3. explicitly set `py_modules` or `packages` with a list of names\r\n",
      "  \u001b[31m   \u001b[0m \r\n",
      "  \u001b[31m   \u001b[0m To find more information, look for \"package discovery\" on setuptools docs.\r\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\r\n",
      "  \r\n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\r\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\r\n",
      "\r\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\r\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\r\n",
      "\r\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\r\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\r\n",
      "\u001b[?25h"
     ]
    }
   ],
   "source": [
    "!pip install git+https://github.com/shahashka/SP-GIES"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "sp_gies",
   "language": "python",
   "name": "sp_gies"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
